apiVersion: apps/v1
kind: Deployment
metadata:
  name: msn-deployment
  namespace: test
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: msn
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: msn
    spec:
      containers:
      - name: fastapi
        image: mehdisn/docker_exercises:latest
        ports:
        - containerPort: 8080
